### ISSUE TITLE
It opens a book with invalid book tag on join

### ISSUE THREAD

**Issue by ColaIan** [Th0rgal/Oraxen#13]
I have fresh installed Oraxen with ProtocolLib, but when I join the server, it opens up a book that says " * Invalid book tag* "

Version: 1.14.4 paper-235
Log: https://paste.pydrox.com/pagehupohi.md
Screenshot: 
![image](https://user-images.githubusercontent.com/43201383/70391066-05f39280-1a0c-11ea-8f4c-586ffbd40c44.png)

**Comment by lRedTeal** [comment]
Try it on spigot

**Comment by Th0rgal** [comment]
Thank you for reporting me the issue, I'll try to reproduce it. I should be able to fix it during the week.

**Comment by Th0rgal** [comment]
Fixed in the last version of oraxen
