### ISSUE TITLE
Better Documentation Please

### ISSUE THREAD

**Issue by Exillium313** [Th0rgal/Oraxen#17]
So ive started with some basics of learning to use this, and im running into issues that I just cant find any documentation on to try and resolve.

I know this plugin is fairly new, but I feel like im lacking the info to actually make use of it.

Everytime I try to add an item, my textures wont load.  I can create items with the default textures.  But mine arent working, when I try to add a model, it defaults to the one of the textures you have provided.  I downloaded a resource pack with a bunch of textures in it, so I know the textures/models arent the problem.  And ive dropped the textures/models into Oraxen/pack, now ive tried them in subfolders and out of sub folders, tried renaming, with and without .json and .png file extensions...

Just feel like I dont have enough documentation to go anywhere with it, and I really love this plugin.

**Comment by Th0rgal** [comment]
Hmm is it working if you load the pack.zip manually?

**Comment by Exillium313** [comment]
It is not, hadnt tried that tbh.  
Would the texture being in a subfolder potentially cause it to not find it?

`dark_shard:
  displayname: '&dDark Shard'
  material: DIAMOND_SWORD
  Pack:
    generate_model: true
    parent_model: item/handheld
    layers:
    - 6.png`

This is what I got atm, 6.png is in a subfolder in Oraxen/pack/textures/new_diamond_sword/6.png

Ive tried replacing moving the textures out of the subfolder, ive tried using just "6" and "6.png"
each time between tests im using /o reload, and checking the /o inv

Only to find this as a texture http://prntscr.com/qt3wdt

Any help would be greatly appreciated!

**Comment by Th0rgal** [comment]
You are using a subfolder so the name isn't 6 but subfolder/6
You can add or remove .png, Oraxen should work. :smile:

**Comment by Exillium313** [comment]
Doesnt work, above I mentioned trying to remove it from the subfolder with no luck.
Texture file location: plugins/Oraxen/pack/textures/108.png

Screenshot of my entry into plugins/Oraxen/items/Custom.yml
http://prntscr.com/qt4dg2

**Comment by Th0rgal** [comment]
How does it look like inside pack.zip? Can you show me the file models/item/diamond_sword.json
?

**Comment by Exillium313** [comment]
models/item/diamond_sword.json:
`{"parent":"item/handheld","textures":{"layer0":"item/diamond_sword"},"overrides":[{"predicate":{"custom_model_data":1},"model":"dark_shard"},{"predicate":{"custom_model_data":2},"model":"storm_sword"},{"predicate":{"custom_model_data":3},"model":"energy_crystal_sword"},{"predicate":{"custom_model_data":4},"model":"dagger"},{"predicate":{"custom_model_data":5},"model":"blood_sword"},{"predicate":{"custom_model_data":6},"model":"katana"},{"predicate":{"custom_model_data":7},"model":"octavia_sword"}]}`

If I download and open pack.zip it looks like this http://prntscr.com/qtqrs3

Sorry for the late reply, I forgot I never posted this.

**Comment by Th0rgal** [comment]
I'm sorry for my late reply, do you still have the same problem?

**Comment by Exillium313** [comment]
Nope I found it was just me misunderstanding how it works, a little better explanation might help future issues but all in all just my lack of understanding how it all works.

Biggest thing being if you change model data for let's say item 3, item 4 , 5 ,6 , etc all lose there models/textures.  Learning this was the biggest revelation because 1 mistake broke everything downstream of what I was messing with.

**Comment by Th0rgal** [comment]
Alright
