### ISSUE TITLE
Plugin Disabled on Paper 1.15.2

### ISSUE THREAD

**Issue by blaukat99** [Th0rgal/Oraxen#18]
So I don't think I have any issues with my configuration, but the plugin is not working on the current latest paper version rn (72). 

Here is my config:

https://pastebin.com/WxaBZqkf

**Comment by Th0rgal** [comment]
Are you using ProtocolLib?

**Comment by blaukat99** [comment]
> Are you using ProtocolLib?

I am, once you texted this I updated to the latest version and Oraxen is still not working.

**Comment by Th0rgal** [comment]
Do you have an error when Oraxen starts?

**Comment by blaukat99** [comment]
This bad boy

https://pastebin.com/TexQxqtH

**Comment by blaukat99** [comment]
jesus all I had to do was delete my recipes files. Thank you for your responses
