### ISSUE TITLE
Possible Solution to Resource Pack Lag

### ISSUE THREAD

**Issue by blaukat99** [Th0rgal/Oraxen#19]
So when you first log into a server with Oraxen you have that moment where you cannot move as the resource pack loads, this can cause issues with mobs attacking you while you log in / general player dissatisfaction. 

A possible solution to this would be to send the player to a different world and put them in spectator mode facing the sky while the pack loads, this makes it a sort of limbo zone so that the player cannot be attacked and can take a moment to breath while the resource pack loads.

Thoughts?

**Comment by Th0rgal** [comment]
Well, while this is a good idea, I don't think this is really something people need since even without resourcepacks people are generally spawned inside a safe area. If you really thing it is important I could try something with packets tho
