### ISSUE TITLE
Can't see recipes.

### ISSUE THREAD

**Issue by Sotlol1** [Th0rgal/Oraxen#24]
I can't see my recipes in-game. Is that intended? This happens when I do "/o recipes and recipes open"

![recipes](https://user-images.githubusercontent.com/6286246/76163593-aa8a8b00-6147-11ea-9694-f688c2ba2889.png)

**Comment by Th0rgal** [comment]
Hello, these are "debug messages", they are going to be replaced by something else in the future but I haven't written it atm.
