### ISSUE TITLE
Can you support MythicMobs plugin to drop Oraxen items?

### ISSUE THREAD

**Issue by yzl210** [Th0rgal/Oraxen#25]
Can you support MythicMobs plugin to drop Oraxen items?
Thank you.

**Comment by yzl210** [comment]
Resolved by myself

**Comment by BiGUNMAN** [comment]
@yzl210 How did you resolve this?

**Comment by yzl210** [comment]
I coded a plugin

**Comment by yzl210** [comment]
[Project page](https://github.com/yzl210/OraxenMythicMobsIntegration)

**Comment by Th0rgal** [comment]
Hey there, I am sorry for the late reply. I take a quick look to the issue and I'm glad you fixed it. Do you want me to merge it with the Oraxen plugin?

**Comment by yzl210** [comment]
Sure

**Comment by yzl210** [comment]
@Th0rgal I opened a pull request.

**Comment by Th0rgal** [comment]
@yzl210 merged!

**Comment by yzl210** [comment]
@Th0rgal What features do you want to add, I can contribute to this plugin.

**Comment by Th0rgal** [comment]
Finish support for shapeless recipes (shaped recipes are already supported) and why notadding furnaces and alambic recipes. This would be awesome. Btw do you want to join the Oraxen organization on github?

**Comment by yzl210** [comment]
Sure

**Comment by yzl210** [comment]
@Th0rgal What is alambic recipe?

**Comment by Th0rgal** [comment]
Basically what is used for creating potions.

**Comment by yzl210** [comment]
@Th0rgal brewing recipe?

**Comment by Th0rgal** [comment]
Yes excuse my english haha, I'm french

**Comment by yzl210** [comment]
I'm a Chinese. Bukkit doesn't seems to provide a Brewing Recipe Class,  so it may take a few days for me to make, I will make a pull request for the shapeless and Furnace Recipe.

**Comment by Th0rgal** [comment]
Alright, this is already amazing!

**Comment by yzl210** [comment]
@Th0rgal Finished Furnace Recipe Builder, made a pull request.
